---
# Uncommend the following section to enable parallel builds
# using the Travis-CI build matrix feature
# FOR DETAILS SEE README!
# env:
#   - kitchen_instance=default-ubuntu-1404
#   - kitchen_instance=default-ubuntu-1604
language: ruby
rvm:
  - 2.3

before_install: "pip install yamllint"
script:
  - yamllint .
