---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: localhost
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  https_proxy: <%= ENV['HTTPS_PROXY'] %>
  no_proxy: localhost,127.0.0.1
  # requirements_path: requirements.yml
  require_ansible_repo: true
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_diff: true
  require_chef_for_busser: false
  ssh_known_hosts:
    - github.com

platforms:
  - name: centos-6
    driver_config:
      network:
        - ['forwarded_port', {guest: 9200, host: 9200}]

verifier:
  name: inspec
  sudo_path: true

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: site.yml

transport:
  max_ssh_sessions: 6
  forward_agent: true
